### ISSUE TITLE
Accessibility in tags

### ISSUE THREAD

**Issue by danielthepope** [danielthepope/imojify#13]
Add `alt` and `title` text to the output of `imojify()`

Change needs to be made in `js/imojify.js` in `imojify_node()`, where the span element is created.

`alt` and `title` text should be the original text inside the colons, but with spaces instead of underscores.

**Comment by AverageMarcus** [comment]
The `alt` attribute will have no bearing as it's not an `<img>` tag. `title` should work but it might be worth looking into [WAI_ARIA](http://www.w3.org/WAI/intro/aria).
