### ISSUE TITLE
Use emoji that I'm actually allowed to use

### ISSUE THREAD

**Issue by danielthepope** [danielthepope/imojify#14]
The Gemoji pack has a strange license. I don't think I'm really allowed to use it.
[Twitter's emoji library](https://github.com/twitter/twemoji) is free to use and beautiful.
[EmojiOne](https://github.com/Ranks/emojione) has a list of emoji names with their descriptions and image names matching the image names in Twemoji.
Let's see if I can link them up.

**Comment by AverageMarcus** [comment]
Is this related to copyrighted images? If so can't you just remove those ones?

**Comment by danielthepope** [comment]
They're _all_ copyrighted... :disappointed: It's weird, the Apple images just seem to have been ripped from OSX and distributed without permission.
Instead the Twitter ones are very clearly licensed, and there's an SVG option too!

**Comment by AverageMarcus** [comment]
Oh thats weird.
