### ISSUE TITLE
handle emoji-less elements

### ISSUE THREAD

**Issue by benfoxall** [danielthepope/imojify#2]
When you use gemojify on an element without any emoji, it fails with `Uncaught TypeError: Cannot read property 'forEach' of null`.  For the JSOxford site - I tweaked it to [skip those elements](https://github.com/jsoxford/jsoxford.github.com/commit/97c2c97282687ad1297722e093bc38d49f0c2574)

**Comment by danielthepope** [comment]
Fixed by removing my long-winded code and using @benfoxall's cool regex capture groups instead :smile:
